final Map<String, String> wordPairs = {
  'house': 'ev',
  'car': 'araba',
  'apple': 'elma',
  'book': 'kitap',
  'dog': 'köpek',
  'cat': 'kedi',
  'tree': 'ağaç',
  'sun': 'güneş',
  'moon': 'ay',
  'water': 'su',
  'fire': 'ateş',
  'earth': 'toprak',
  'sky': 'gökyüzü',
  'bird': 'kuş',
  'fish': 'balık',
  'mountain': 'dağ',
  'river': 'nehir',
  'ocean': 'okyanus',
  'lake': 'göl',
  'grass': 'çim',
  'flower': 'çiçek',
  'leaf': 'yaprak',
  'rock': 'kaya',
  'sand': 'kum',
  'cloud': 'bulut',
  'rain': 'yağmur',
  'snow': 'kar',
  'wind': 'rüzgar',
  'light': 'ışık',
  'dark': 'karanlık',
  'day': 'gün',
  'night': 'gece',
  'time': 'zaman',
  'clock': 'saat',
  'watch': 'kol saati',
  'phone': 'telefon',
  'bed': 'yatak',
  'door': 'kapı',
  'window': 'pencere',
  'roof': 'çatı',
  'wall': 'duvar',
  'floor': 'zemin',
  'street': 'cadde',
  'city': 'şehir',
  'country': 'ülke',
  'village': 'köy',
  'market': 'pazar',
  'shop': 'dükkan',
  'food': 'yiyecek',
  'drink': 'içecek',
  'bread': 'ekmek',
  'meat': 'et',
  'fruit': 'meyve',
  'vegetable': 'sebze',
  'salt': 'tuz',
  'sugar': 'şeker',
  'cake': 'pasta',
  'ice': 'buz',
  'milk': 'süt',
  'coffee': 'kahve',
  'tea': 'çay',
  'beer': 'bira',
  'wine': 'şarap',
  'chocolate': 'çikolata',
  'candy': 'şekerleme',
  'toy': 'oyuncak',
  'game': 'oyun',
  'music': 'müzik',
  'dance': 'dans',
  'song': 'şarkı',
  'film': 'film',
  'art': 'sanat',
  'paint': 'boya',
  'color': 'renk',
  'picture': 'resim',
  'story': 'hikaye',
  'teacher': 'öğretmen',
  'student': 'öğrenci',
  'lesson': 'ders',
  'homework': 'ödev',
  'test': 'sınav',
  'grade': 'not',
  'subject': 'ders',
  'science': 'bilim',
  'math': 'matematik',
  'history': 'tarih',
  'language': 'dil',
  'chair': 'sandalye',
  'computer': 'bilgisayar',
  'carpet': 'halı',
  'lamp': 'lamba',
  'glass': 'cam',
  'cup': 'kupa',
  'spoon': 'kaşık',
  'fork': 'çatal',
  'knife': 'bıçak',
  'plate': 'tabak',
  'bowl': 'kase',
  'kitchen': 'mutfak',
  'bathroom': 'banyo',
  'bedroom': 'yatak odası',
  'livingroom': 'oturma odası',
  'garden': 'bahçe',
  'garage': 'garaj',
  'office': 'ofis',
  'hospital': 'hastane',
  'bank': 'banka',
  'post': 'posta',
  'firefighter': 'itfaiyeci',
  'doctor': 'doktor',
  'nurse': 'hemşire',
  'engineer': 'mühendis',
  'scientist': 'bilim insanı',
  'artist': 'sanatçı',
  'musician': 'müzisyen',
  'writer': 'yazar',
  'farmer': 'çiftçi',
  'soldier': 'asker',
  'police': 'polis',
  'pilot': 'pilot',
  'chef': 'şef',
  'baker': 'fırıncı',
  'waiter': 'garson',
  'cashier': 'kasiyer',
  'designer': 'tasarımcı',
  'architect': 'mimar',
  'developer': 'geliştirici',
  'worker': 'işçi',
  'manager': 'yönetici',
  'leader': 'lider',
  'follower': 'takipçi',
  'parent': 'ebeveyn',
  'child': 'çocuk',
  'sibling': 'kardeş',
  'friend': 'arkadaş',
  'neighbor': 'komşu',
  'couple': 'çift',
  'family': 'aile',
  'team': 'takım',
  'group': 'grup',
  'community': 'toplum',
  'society': 'toplum',
  'nation': 'millet',
  'culture': 'kültür',
  'tradition': 'gelenek',
  'festival': 'festival',
  'holiday': 'tatil',
  'event': 'etkinlik',
  'ceremony': 'tören',
  'celebration': 'kutlama',
  'party': 'parti',
  'concert': 'konser',
  'show': 'gösteri',
  'theater': 'tiyatro',
  'museum': 'müze',
  'gallery': 'galeri',
  'exhibition': 'sergi',
  'artwork': 'sanat eseri',
  'portrait': 'portre',
  'landscape': 'manzara',
  'photograph': 'fotoğraf',
  'painting': 'tablo',
  'drawing': 'çizim',
  'sketch': 'eskiz',
  'craft': 'zanaat',
  'handicraft': 'el sanatı',
  'gift': 'hediye',
  'present': 'sunum',
  'souvenir': 'hatıra',
  'memento': 'anı',
  'token': 'jeton',
  'relic': 'kalıntı',
  'artifact': 'eser',
  'memory': 'hafıza',
  'remembrance': 'anımsama',
  'legacy': 'miras',
  'heritage': 'kültürel miras',
  'journey': 'seyahat',
  'adventure': 'macera',
  'trip': 'gezi',
  'voyage': 'sefer',
  'expedition': 'keşif',
  'tour': 'tur',
  'cruise': 'seyahat',
  'destination': 'varış yeri',
  'rocket': 'roket',
  'television': 'televizyon',
  'keyboard': 'klavye',
  'mouse': 'fare',
  'tablet': 'tablet',
  'camera': 'kamera',
  'wallet': 'cüzdan',
  'scarf': 'atkı',
  'socks': 'çorap',
  'shoes': 'ayakkabı',
  'jacket': 'ceket',
  'sweater': 'kazak',
  'belt': 'kemer',
  'gloves': 'eldiven',
  'umbrella': 'şemsiye',
  'purse': 'çanta',
  'ring': 'yüzük',
  'necklace': 'kolye',
  'earrings': 'küpe',
  'bracelet': 'bilezik',
  'crown': 'taç',
  'flag': 'bayrak',
  'hammock': 'hamak',
  'tent': 'çadır',
  'compass': 'pusula',
  'map': 'harita',
  'lantern': 'fener',
  'binoculars': 'dürbün',
  'backpack': 'sırt çantası',
  'saddle': 'seles',
  'paddle': 'pala',
  'surfboard': 'sörf tahtası',
  'skateboard': 'kaykay',
  'bicycle': 'bisiklet',
  'motorcycle': 'motosiklet',
  'helicopter': 'helikopter',
  'submarine': 'denizaltı',
  'plane': 'uçak',
  'astronaut': 'astronot',
  'starfish': 'denizyıldızı',
  'crab': 'yengeç',
  'lobster': 'ıstakoz',
  'whale': 'balina',
  'dolphin': 'yunus',
  'shark': 'köpek balığı',
  'octopus': 'ahtapot',
  'seaweed': 'deniz yosunu',
  'coral': 'mercankaya',
  'clownfish': 'palyaço balığı',
  'sea turtle': 'deniz kaplumbağası',
  'sea horse': 'deniz atı',
  'jellyfish': 'denizanası',
  'barnacle': 'sünger',
  'mussel': 'midye',
  'clam': 'istiridye',
  'oyster': 'istiridye',
  'squid': 'kalamar',
  'piranha': 'piranha',
  'tuna': 'ton balığı',
  'salmon': 'somon',
  'trout': 'alabalık',
  'catfish': 'kedi balığı',
  'goldfish': 'altın balık',
  'eagle': 'kartal',
  'sparrow': 'serçe',
  'parrot': 'papagan',
  'owl': 'baykuş',
  'penguin': 'penguen',
  'flamingo': 'flamingo',
  'peacock': 'tavus kuşu',
  'pigeon': 'güvercin',
  'crow': 'karga',
  'hummingbird': 'salkım kuşu',
  'stork': 'leylek',
  'crane': 'turna',
  'robin': 'robin',
  'swallow': 'yutkunma',
  'hatchling': 'yavru kuş',
  'egg': 'yumurta',
  'nest': 'yuva',
  'feather': 'tüy',
  'wing': 'kanat',
  'beak': 'gaga',
  'zebra': 'zebra',
  'lion': 'aslan',
  'tiger': 'kaplan',
  'bear': 'ayı',
  'elephant': 'fil',
  'giraffe': 'zürafa',
  'kangaroo': 'kanguru',
  'monkey': 'maymun',
  'hippopotamus': 'hipopotam',
  'rhinoceros': 'tek boynuzlu',
  'wolf': 'kurt',
  'fox': 'tilki',
  'deer': 'geyik',
  'rabbit': 'tavşan',
  'squirrel': 'sincap',
  'panda': 'panda',
  'koala': 'koala',
  'otter': 'su samuru',
  'beaver': 'kunduz',
  'hedgehog': 'kirpi',
  'ferret': 'furet',
  'weasel': 'sansar',
  'bat': 'yarasa',
  'parakeet': 'muhabbet kuşu',
  'canary': 'kanarya',
  'finch': 'saka',
  'rooster': 'horoz',
  'chicken': 'tavuk',
  'duck': 'ördek',
  'goose': 'kaz',
  'turkey': 'hindi',
  'peahen': 'tavus kuşu dişi',
  'swan': 'kuğu',
  'ostrich': 'devekuşu',
  'emu': 'emu',
  'kiwi': 'kiwi',
  'albatross': 'albatros',
  'heron': 'kamışlık kuşu',
  'pelican': 'pelikan',
  'cormorant': 'dalgıç kuşu',
  'hawk': 'şahin',
  'falcon': 'şahin',
  'vulture': 'akbabalar',
  'condor': 'kondor',
  'viper': 'yılan',
  'cobra': 'kobra',
  'python': 'piton',
  'chameleon': 'bukalemun',
  'gecko': 'gecko',
  'iguana': 'igvana',
  'lizard': 'kertenkele',
  'tortoise': 'kaplumbağa',
  'snake': 'yılan',
  'frog': 'kurbağa',
  'toad': 'gölet kurbağası',
  'newt': 'salamandra',
  'salamander': 'salamandra',
  'herring': 'sardalya',
  'mackerel': 'uskumru',
  'sardine': 'sardalya',
  'seal': 'fok',
  'walrus': 'mürekkep balığı',
  'urchin': 'deniz kestanesi',
  'anemone': 'deniz anemonu',
  'seahorse': 'deniz atı',
  'sunshine': 'güneş ışığı',
  'cloudy': 'bulutlu',
  'rainy': 'yağmurlu',
  'stormy': 'fırtınalı',
  'windy': 'rüzgarlı',
  'temperature': 'sıcaklık',
  'humidity': 'nem',
  'forecast': 'hava durumu',
  'season': 'mevsim',
  'year': 'yıl',
  'month': 'ay',
  'week': 'hafta',
  'daylight': 'gündüz ışığı',
  'sunrise': 'güneş doğuşu',
  'sunset': 'güneş batışı',
  'dusk': 'alacakaranlık',
  'dawn': 'şafak',
  'timezone': 'zaman dilimi',
  'calendar': 'takvim',
  'wedding': 'düğün',
  'anniversary': 'yıldönümü',
  'birthday': 'doğum günü',
  'graduation': 'mezuniyet',
  'vacation': 'tatil',
  'travel': 'seyahat',
  'exploration': 'keşif',
  'excursion': 'gezinti',
  'guide': 'rehber',
  'itinerary': 'seyahat programı',
  'transportation': 'ulaşım',
  'vehicle': 'araç',
  'bus': 'otobüs',
  'train': 'tren',
  'boat': 'bot',
  'ship': 'gemi',
  'traffic': 'trafik',
  'road': 'yol',
  'highway': 'otoyol',
  'intersection': 'kavşak',
  'roundabout': 'dönel kavşak',
  'bridge': 'köprü',
  'tunnel': 'tünel',
  'building': 'bina',
  'skyscraper': 'gökdelen',
  'apartment': 'daire',
  'factory': 'fabrika',
  'store': 'mağaza',
  'restaurant': 'restoran',
  'cafe': 'kafe',
  'bar': 'bar',
  'gym': 'spor salonu',
  'park': 'park',
  'field': 'alan',
  'court': 'mahkeme',
  'library': 'kütüphane',
  'clinic': 'klinik',
  'marketplace': 'pazar yeri',
  'shopping': 'alışveriş',
  'sale': 'indirim',
  'software': 'yazılım',
  'hardware': 'donanım',
  'internet': 'internet',
  'website': 'web sitesi',
  'application': 'uygulama',
  'program': 'program',
  'data': 'veri',
  'database': 'veritabanı',
  'network': 'ağ',
  'security': 'güvenlik',
  'firewall': 'güvenlik duvarı',
  'encryption': 'şifreleme',
  'password': 'şifre',
  'username': 'kullanıcı adı',
  'email': 'e-posta',
  'document': 'belge',
  'file': 'dosya',
  'folder': 'kıyt',
  'upload': 'yükle',
  'download': 'indir',
  'backup': 'yedekleme',
  'restore': 'geri yükleme',
  'maintenance': 'bakım',
  'upgrade': 'yükseltme',
  'update': 'güncelleme',
  'system': 'sistem',
  'monitor': 'monitör',
  'screen': 'ekran',
  'printer': 'yazıcı',
  'scanner': 'tarayıcı',
  'speaker': 'hoparlör',
  'headphone': 'kulaklık',
  'microphone': 'mikrofon',
  'projector': 'projektör',
  'presentation': 'sunum',
  'slide': 'slayt',
  'chart': 'grafik',
  'graph': 'grafik',
  'spreadsheet': 'elektronik tablo',
  'statistics': 'istatistik',
  'analysis': 'analiz',
  'report': 'rapor',
  'summary': 'özet',
  'meeting': 'toplantı',
  'conference': 'konferans',
  'seminar': 'seminer',
  'workshop': 'atölye',
  'training': 'eğitim',
  'session': 'oturum',
  'discussion': 'tartışma',
  'feedback': 'geri bildirim',
  'evaluation': 'değerlendirme',
  'assessment': 'değerlendirme',
  'score': 'puan',
  'exam': 'sınav',
  'qualification': 'nitelik',
  'certification': 'sertifika',
  'license': 'lisans',
  'registration': 'kayıt',
  'approval': 'onay',
  'rejection': 'reddetme',
  'submission': 'başvuru',
  'deadline': 'son tarih',
  'schedule': 'program',
  'appointment': 'randevu',
  'reminder': 'hatırlatma',
  'banana': 'muz',
  'orange': 'portakal',
  'grape': 'üzüm',
  'peach': 'şeftali',
  'plum': 'eroz',
  'lemon': 'limon',
  'watermelon': 'karpuz',
  'coconut': 'hindistan cevizi',
  'strawberry': 'çilek',
  'blueberry': 'yaban mersini',
  'pineapple': 'ananas',
  'mango': 'mango',
  'cucumber': 'salatalık',
  'tomato': 'domates',
  'pepper': 'biber',
  'carrot': 'havuç',
  'onion': 'soğan',
  'garlic': 'sarımsak',
  'potato': 'patates',
  'lettuce': 'marul',
  'spinach': 'ıspanak',
  'broccoli': 'brokoli',
  'cauliflower': 'karnabahar',
  'zucchini': 'kabak',
  'eggplant': 'patlıcan',
  'bean': 'fasulye',
  'pea': 'bezelye',
  'chickpea': 'nohut',
  'lentil': 'mercimek',
  'rice': 'pirinç',
  'pasta': 'makarna',
  'butter': 'tereyağı',
  'cheese': 'peynir',
  'yogurt': 'yoğurt',
  'sour cream': 'ekşi krema',
  'olive oil': 'zeytinyağı',
  'vinegar': 'sirke',
  'spice': 'baharat',
  'herb': 'ot',
  'seasoning': 'baharat karışımı',
  'syrup': 'şurup',
  'jam': 'reçel',
  'honey': 'bal',
  'sauce': 'sos',
  'ketchup': 'ketchup',
  'mayonnaise': 'mayonez',
  'mustard': 'hardal',
  'barbecue': 'ızgara',
  'cooking': 'pişirme',
  'grilling': 'ızgara',
  'frying': 'kızartma',
  'boiling': 'kaynatma',
  'roasting': 'kızartma',
  'baking': 'fırınlama',
  'steaming': 'buharda pişirme',
  'marinating': 'marine etme',
  'garnish': 'süsleme',
  'dish': 'tabak',
  'meal': 'yemek',
  'course': 'kurs',
  'snack': 'atıştırmalık',
  'breakfast': 'kahvaltı',
  'lunch': 'öğle yemeği',
  'dinner': 'akşam yemeği',
  'dessert': 'tatlı',
  'appetizer': 'meze',
  'beverage': 'içecek',
  'smoothie': 'sorbe',
  'juice': 'meyve suyu',
  'cocktail': 'kokteyl',
  'mocktail': 'alkolsüz kokteyl',
  'soda': 'gazlı içecek',
  'shake': 'milkshake',
  'pudding': 'puding',
  'sorbet': 'sorbe',
  'star': 'yıldız',
  'table': 'masa',
  'class': 'sınıf',
  'space': 'uzay',
  'universe': 'evren',
  'galaxy': 'galaksi',
  'planet': 'gezegen',
  'starship': 'uzay gemisi',
  'satellite': 'uydu',
  'telescope': 'teleskop',
  'orbit': 'yörünge',
  'gravity': 'yerçekimi',
  'blackhole': 'kara delik',
  'wormhole': 'solucan deliği',
  'time travel': 'zaman yolculuğu',
  'dimension': 'boyut',
  'multiverse': 'çoklu evren',
  'theory': 'teori',
  'hypothesis': 'hipotez',
  'experiment': 'deney',
  'observation': 'gözlem',
  'research': 'araştırma',
  'result': 'sonuç',
  'conclusion': 'sonuç',
  'knowledge': 'bilgi',
  'wisdom': 'bilgelik',
  'truth': 'gerçek',
  'fact': 'gerçek',
  'opinion': 'görüş',
  'belief': 'inanç',
  'faith': 'iman',
  'trust': 'güven',
  'hope': 'umut',
  'love': 'aşk',
  'happiness': 'mutluluk',
  'sadness': 'üzüntü',
  'anger': 'öfke',
  'fear': 'korku',
  'surprise': 'sürpriz',
  'disgust': 'tiksinti',
  'emotion': 'duygu',
  'feeling': 'hissetme',
  'sensation': 'duyu',
  'mood': 'ruh hali',
  'state': 'durum',
  'condition': 'koşul',
  'situation': 'durum',
  'context': 'bağlam',
  'environment': 'çevre',
  'nature': 'doğa',
  'world': 'dünya',
  'ecosystem': 'ekosistem',
  'climate': 'iklim',
  'weather': 'hava durumu',
  'pollution': 'kirlilik',
  'conservation': 'koruma',
  'sustainability': 'sürdürülebilirlik',
  'resource': 'kaynak',
  'energy': 'enerji',
  'power': 'güç',
  'electricity': 'elektrik',
  'solar': 'güneş',
  'fuel': 'yakıt',
  'gas': 'gaz',
  'oil': 'yağ',
  'coal': 'kömür',
  'nuclear': 'nükleer',
  'renewable': 'yenilenebilir',
  'technology': 'teknoloji',
  'innovation': 'yenilik',
  'development': 'gelişme',
  'progress': 'ilerleme',
  'future': 'gelecek',
  'past': 'geçmiş',
  'moment': 'an',
  'age': 'yaş',
  'century': 'yüzyıl',
  'era': 'çağ',
  'period': 'dönem',
  'experience': 'deneyim',
  'skill': 'beceri',
  'talent': 'yeteneği',
  'ability': 'yetki',
  'capacity': 'kapasite',
  'potential': 'potansiyel',
  'goal': 'amaç',
  'objective': 'hedef',
  'dream': 'hayal',
  'aspiration': 'hedef',
  'ambition': 'hırs',
  'success': 'başarı',
  'failure': 'başarısızlık',
  'challenge': 'zorluk',
  'opportunity': 'fırsat',
  'risk': 'risk',
  'decision': 'karar',
  'choice': 'seçim',
  'option': 'seçenek',
  'strategy': 'strateji',
  'plan': 'plan',
  'method': 'yöntem',
  'approach': 'yaklaşım',
  'tactic': 'taktik',
  'solution': 'çözüm',
  'problem': 'sorun',
  'question': 'soru',
  'issue': 'konu',
  'debate': 'tartışma',
  'argument': 'tartışma',
  'persuasion': 'ikna',
  'conviction': 'inanç',
  'certainty': 'kesinlik',
  'doubt': 'şüphe',
  'confusion': 'karışıklık',
  'clarity': 'netlik',
  'understanding': 'anlayış',
  'insight': 'içgörü',
  'realization': 'farkındalık',
  'awareness': 'farkındalık',
  'perception': 'algı',
  'perspective': 'perspektif',
  'viewpoint': 'bakış açısı',
  'standpoint': 'noktası',
  'attitude': 'tutum',
  'behavior': 'davranış',
  'response': 'tepki',
  'reaction': 'reaksiyon',
  'interaction': 'etkileşim',
  'communication': 'iletişim',
  'speech': 'konuşma',
  'dialogue': 'diyalog',
  'conversation': 'sohbet',
  'lecture': 'ders',
  'education': 'eğitim',
  'school': 'okul',
  'college': 'üniversite',
  'university': 'üniversite',
  'degree': 'derece',
  'diploma': 'diploma',
  'topic': 'konu',
  'material': 'malzeme',
  'textbook': 'ders kitabı',
  'handbook': 'el kitabı',
  'manual': 'kılavuz',
  'reference': 'referans',
  'information': 'bilgi',
  'learning': 'öğrenme',
  'practice': 'pratik',
  'exercise': 'egzersiz',
  'improvement': 'gelişme',
  'growth': 'büyüme',
  'achievement': 'başarı',
  'aim': 'amaç',
  'desire': 'istek',
  'motivation': 'motivasyon',
  'inspiration': 'ilham',
  'passion': 'tutku',
  'enthusiasm': 'heves',
  'drive': 'istek',
  'determination': 'kararlılık',
  'commitment': 'bağlılık',
  'dedication': 'özveri',
  'persistence': 'sebat',
  'resilience': 'dayanıklılık',
  'courage': 'cesaret',
  'bravery': 'cesaret',
  'strength': 'güç',
  'confidence': 'özgüven',
  'self-esteem': 'özsaygı',
  'self-worth': 'öz değer',
  'self-awareness': 'öz farkındalık',
  'self-improvement': 'öz gelişim',
  'transformation': 'dönüşüm',
  'change': 'değişim',
  'evolution': 'evrim',
  'advancement': 'ilerleme',
  'creativity': 'yaratıcılık',
  'imagination': 'hayal gücü',
  'originality': 'orijinallik',
  'vision': 'vizyon',
  'fantasy': 'hayal',
  'illusion': 'illüzyon',
  'reality': 'gerçeklik',
  'friendship': 'arkadaşlık',
  'civilization': 'medeni̇yet',
  'government': 'hükümet',
  'politics': 'siyaset',
  'law': 'hukuk',
  'justice': 'adalet',
  'rights': 'haklar',
  'freedom': 'özgürlük',
  'equality': 'eşitlik',
  'diversity': 'çeşitlilik',
  'inclusion': 'dahil etme',
  'tolerance': 'hoşgörü',
  'respect': 'saygı',
  'empathy': 'empati',
  'compassion': 'merhamet',
  'kindness': 'nazik',
  'generosity': 'cömertlik',
  'charity': 'hayırseverlik',
  'philanthropy': 'hayırseverlik',
  'volunteerism': 'gönüllülük',
  'service': 'hizmet',
  'help': 'yardım',
  'support': 'destek',
  'cooperation': 'işbirliği',
  'collaboration': 'işbirliği',
  'teamwork': 'takım çalışması',
  'partnership': 'ortaklık',
  'networking': 'ağ oluşturma',
  'relationship': 'ilişki',
  'connection': 'bağlantı',
  'bond': 'bağ',
  'romance': 'romantik',
  'affection': 'şefkat',
  'intimacy': 'yakınlık',
  'loyalty': 'sadakat',
  'devotion': 'fedakarlık',
  'responsibility': 'sorumluluk',
  'accountability': 'hesap verebilirlik',
  'integrity': 'bütünlük',
  'honesty': 'dürüstlük',
  'transparency': 'şeffaflık',
  'trustworthiness': 'güvenilirlik',
  'reliability': 'güvenilirlik',
  'authenticity': 'otantik olma',
  'credibility': 'güvenilirlik',
  'validity': 'geçerlilik',
  'accuracy': 'doğruluk',
  'precision': 'kesinlik',
  'consistency': 'tutarlılık',
  'continuity': 'devamlılık',
  'stability': 'istikrar',
  'balance': 'denge',
  'harmony': 'uyum',
  'peace': 'barış',
  'calm': 'sakin',
  'serenity': 'huzur',
  'tranquility': 'sakinlik',
  'joy': 'sevinç',
  'contentment': 'tatmin',
  'satisfaction': 'memnuniyet',
  'gratitude': 'minnet',
  'appreciation': 'takdir',
  'thankfulness': 'şükran',
  'sympathy': 'sempati',
  'caring': 'ilgilenme',
  'nurturing': 'besleyici',
  'supportive': 'destekleyici',
  'encouraging': 'cesaretlendirici',
  'helpful': 'yararlı',
  'friendly': 'dostça',
  'warm': 'sıcak',
  'welcoming': 'karşılayıcı',
  'inclusive': 'kapsayıcı',
  'diverse': 'çeşitli',
  'accepting': 'kabul edici',
  'tolerant': 'hoşgörülü',
  'open-minded': 'açık fikirli',
  'curious': 'meraklı',
  'inquisitive': 'soru soran',
  'explorative': 'keşfeden',
  'adventurous': 'macera arayan',
  'bold': 'cesur',
  'fearless': 'korkusuz',
  'determined': 'kararlı',
  'persistent': 'inatçı',
  'resilient': 'dayanıklı',
  'adaptable': 'uyum sağlayan',
  'flexible': 'esnek',
  'creative': 'yaratıcı',
  'innovative': 'yenilikçi',
  'imaginative': 'hayal gücü olan',
  'original': 'orijinal',
  'visionary': 'vizyon sahibi',
  'forward-thinking': 'ilerici düşünceli',
  'progressive': 'ilerici',
  'transformative': 'dönüştürücü',
  'revolutionary': 'devrimci',
  'groundbreaking': 'çığır açan',
  'impactful': 'etkili',
  'meaningful': 'anlamlı',
  'significant': 'önemli',
  'valuable': 'değerli',
  'essential': 'temel',
  'critical': 'kritik',
  'necessary': 'gerekli',
  'important': 'önemli',
  'useful': 'yararlı',
  'beneficial': 'faydalı',
  'advantageous': 'avantajlı',
  'worthwhile': 'değerlidir',
  'rewarding': 'ödüllendirici',
  'fulfilling': 'tatmin edici',
  'satisfying': 'tatmin edici',
  'enriching': 'zenginleştirici',
  'enjoyable': 'eğlenceli',
  'pleasurable': 'haz verici',
  'fun': 'eğlence',
  'exciting': 'heyecan verici',
  'thrilling': 'heyecanlandırıcı',
  'entertaining': 'eğlendirici',
  'stimulating': 'uyarıcı',
  'inspiring': 'ilham verici',
  'motivating': 'motive edici',
  'uplifting': 'moral verici',
  'energizing': 'enerji veren',
  'invigorating': 'canlandırıcı',
  'refreshing': 'ferahlatıcı',
  'rejuvenating': 'gençleştirici',
  'revitalizing': 'canlandırıcı',
  'renewing': 'yenileyici',
  'restorative': 'iyileştirici',
  'healing': 'şifa',
  'therapeutic': 'terapötik',
  'compassionate': 'şefkatli',
  'loving': 'sevgili',
  'gentle': 'nazik',
  'soft': 'yumuşak',
  'kind': 'nazik',
  'hospitable': 'misafirperver',
  'gracious': 'nazik',
  'polite': 'nazik',
  'courteous': 'nazik',
  'respectful': 'saygılı',
  'considerate': 'düşünceli',
  'thoughtful': 'düşünceli',
  'empathetic': 'empatik',
  'positive': 'pozitif',
  'optimistic': 'iyimser',
  'hopeful': 'umutlu',
  'confident': 'kendine güvenen',
  'assured': 'emin',
  'secure': 'güvende',
  'safe': 'güvenli',
  'trusting': 'güvenen',
  'trustworthy': 'güvenilir',
  'reliable': 'güvenilir',
  'dependable': 'güvenilir',
  'faithful': 'sadık',
  'loyal': 'sadık',
  'devoted': 'sadık',
  'dedicated': 'özenle çalışan',
  'committed': 'bağlı',
  'fervent': 'tutkulu',
  'passionate': 'tutkulu',
  'zealous': 'şevkli',
  'enthusiastic': 'heyecanlı',
  'eager': 'hevesli',
  'excited': 'heyecanlı',
  'interested': 'ilgili',
  'engaged': 'katılımcı',
  'involved': 'katılan',
  'invested': 'yatırım yapan',
  'motivated': 'motivasyonlu',
  'driven': 'hırslı',
  'focused': 'odaklı',
  'tenacious': 'inatçı',
  'hardworking': 'çalışkan',
  'diligent': 'özenli',
  'conscientious': 'özenli',
  'responsible': 'sorumlu',
  'accountable': 'hesap verebilir',
  'honest': 'dürüst',
  'sincere': 'samimi',
  'genuine': 'gerçek',
  'authentic': 'otantik',
  'transparent': 'şeffaf',
  'forthright': 'açık sözlü',
  'straightforward': 'doğrudan',
  'direct': 'doğrudan',
  'candid': 'samimi',
  'frank': 'açık sözlü',
  'open': 'açık',
  'receptive': 'açık fikirli',
  'forgiving': 'bağışlayıcı',
  'kind-hearted': 'iyi kalpli',
  'humane': 'insani',
  'charitable': 'hayırsever',
  'altruistic': 'fedakar',
  'selfless': 'kendini feda eden',
  'generous': 'cömert',
  'magnanimous': 'büyük yürekli',
  'philanthropic': 'hayırsever',
  'beneficent': 'hayırsever',
  'noble': 'soylu',
  'honorable': 'onurlu',
  'virtuous': 'erdemli',
  'righteous': 'doğru',
  'just': 'adaletli',
  'fair': 'adil',
  'equitable': 'eşitlikçi',
  'impartial': 'tarafsız',
  'neutral': 'nötr',
  'disinterested': 'çıkar gözetmeyen',
  'unbiased': 'tarafsız',
  'unprejudiced': 'ön yargısız',
  'multicultural': 'çok kültürlü',
  'cosmopolitan': 'kozmopolit',
  'global': 'küresel',
  'universal': 'evrensel',
  'transnational': 'uluslararası',
  'cross-cultural': 'kültürler arası',
  'intercultural': 'kültürler arası',
  'cross-disciplinary': 'disiplinler arası',
  'collaborative': 'işbirlikçi',
  'cooperative': 'işbirlikçi',
  'partnership-based': 'ortaklığa dayalı',
  'team-oriented': 'takım odaklı',
  'networked': 'ağlı',
  'community-oriented': 'topluluk odaklı',
  'relationship-focused': 'ilişki odaklı',
  'people-centered': 'insan odaklı',
  'human-centered': 'insan merkezli',
  'open-hearted': 'açık kalpli',
  'meticulous': 'titiz',
  'scrupulous': 'titiz',
  'attentive': 'dikkatli',
  'observant': 'gözlemci',
  'careful': 'dikkatli',
  'prudent': 'tedbirli',
  'cautious': 'dikkatli',
  'wise': 'bilge',
  'sensible': 'mantıklı',
  'insightful': 'anlayışlı',
  'perceptive': 'algılama',
  'shrewd': 'zekice',
  'astute': 'zekice',
  'clever': 'zeki',
  'intelligent': 'zeki',
  'smart': 'akıllı',
  'bright': 'parlak',
  'brilliant': 'parlak',
  'gifted': 'yetenekli',
  'talented': 'yetenekli',
  'capable': 'yetkin',
  'skilled': 'yetenekli',
  'expert': 'uzman',
  'proficient': 'uzman',
  'experienced': 'deneyimli',
  'knowledgeable': 'bilgili',
  'sensitive': 'duyarlı',
  'responsive': 'duyarlı',
  'tactile': 'dokunsal',
  'emotionally intelligent': 'duygusal zeka',
  'socially aware': 'toplumsal farkındalık',
  'culturally competent': 'kültürel yeterlilik',
  'contextually aware': 'bağlamsal farkındalık',
  'ethically sensitive': 'etik duyarlılık',
  'morally aware': 'ahlaki farkındalık',
  'spiritually aware': 'ruhsal farkındalık',
  'philosophically minded': 'felsefi zihin',
  'logically inclined': 'mantıksal eğilim',
  'analytically minded': 'analitik zihin',
  'systematic': 'sistematik',
  'methodical': 'metodik',
  'strategic': 'stratejik',
  'tactical': 'taktik',
  'organized': 'organize',
  'efficient': 'verimli',
};
